name: Build
on:
  push: 
    branch:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Patch and build
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace
          ./gradlew createReobfPaperclipJar --stacktrace
      - name: Get version
        run: |
          echo "::set-output name=version::$(grep version gradle.properties | cut -d "=" -f2 | sed -e 's/^[[:space:]]*//')"
          echo "::set-output name=mcversion::$(grep mcVersion gradle.properties | cut -d "=" -f2 | sed -e 's/^[[:space:]]*//')"
        id: version
      - name: Setup release jar
        run: |
          mkdir -p target
          cp ./build/libs/pearl-paperclip-${{ steps.version.outputs.version }}-reobf.jar ./target/Pearl-${{ steps.version.outputs.mcversion }}.jar
      - name: Archive Paperclip
        uses: actions/upload-artifact@v2
        with:
          name: "Pearl-${{ steps.version.outputs.mcversion }}"
          path: ./target/Pearl-${{ steps.version.outputs.mcversion }}.jar
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.mcversion }}"
          prerelease: false
          title: "Pearl ${{ steps.version.outputs.mcversion }}"
          files: ./target/Pearl-${{ steps.version.outputs.mcversion }}.jar
